"""Single source of truth for shared settings across the whole project.

Imported by:
  * augmentation_pipeline.ipynb
  * cnn_transfer.ipynb
  * deploy.py

Change a value here and it takes effect in all three. To try a different
value in one notebook without touching this file, just reassign after
`from vision_config import *`.

Layout of the repo (paths below are relative to PROJECT_ROOT):
  data/images/          — source images (.png)
  data/labels/       — YOLO polygon labels (class x1 y1 x2 y2 ...)
  data/labels_bbox/  — YOLO bbox labels    (class cx cy w h)
                            auto-generated by augmentation_pipeline.ipynb §3
  yolo_dataset/           — BUILD ARTIFACT: symlink-based train/val split that
                            Ultralytics wants. Real files live in data/.
  runs_cnn_transfer/      — all training runs (weights, metrics, plots)
"""
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent

# ---------------------------------------------------------------------------
# Data paths
# ---------------------------------------------------------------------------
IMAGES_DIR  = PROJECT_ROOT / 'data' / 'images'
POLY_LABELS = PROJECT_ROOT / 'data' / 'labels'
BBOX_LABELS = PROJECT_ROOT / 'data' / 'labels_bbox'

RUNS_DIR    = PROJECT_ROOT / 'runs_cnn_transfer'
YOLO_DATASET_DIR = PROJECT_ROOT / 'yolo_dataset'


# ---------------------------------------------------------------------------
# Label kind — flip to switch the entire pipeline
# ---------------------------------------------------------------------------
# 'polygon' → instance segmentation (reads POLY_LABELS, uses yolo11n-seg.pt)
# 'bbox'    → detection only        (reads BBOX_LABELS, uses yolo11n.pt)
LABEL_KIND = 'polygon'


# ---------------------------------------------------------------------------
# Classes
# ---------------------------------------------------------------------------
CLASS_NAMES = {0: 'firetruck', 1: 'fire', 2: 'ambulance', 3: 'blood'}
NUM_CLASSES = len(CLASS_NAMES)


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------
IMAGE_SIZE   = 720
VAL_FRACTION = 0.20
SEED         = 1337
FT_EPOCHS    = 100
FT_BATCH     = 8

# Section B (SupCon) — opt-in
SUPCON_EPOCHS   = 30
SUPCON_BATCH    = 16
SUPCON_TEMP     = 0.1
SUPCON_PROJ_DIM = 128

# Section C (DINO) — gated
GATE_MIN_UNLABELED = 500
DINO_EPOCHS        = 50
DINO_BATCH         = 32
DINO_TEMP_STUDENT  = 0.1
DINO_TEMP_TEACHER  = 0.04
DINO_EMA           = 0.996


# ---------------------------------------------------------------------------
# Augmentation
# ---------------------------------------------------------------------------
AUG_PROBS = dict(
    h_flip          = 0.5,
    v_flip          = 0.1,
    rotate_90       = 0.3,
    rotate_small    = 0.5,
    affine_skew     = 0.3,
    random_crop     = 0.5,
    color_jitter    = 0.5,
    color_gradient  = 0.5,   # smooth spatial RGB tint (some regions warmer/cooler)
    hue_rotate      = 0.3,   # full hue rotation chance (reds -> blue, etc.)
    channel_dropout = 0.10,
    cutout          = 0.5,
    gauss_noise     = 0.3,
    gauss_blur      = 0.3,
    sobel           = 0.08,
)
CROP_SCALE   = (0.6, 1.0)
ROTATE_DEG   = 20
SKEW_DEG     = 10
CUTOUT_HOLES = (1, 4)
CUTOUT_FRAC  = (0.05, 0.12)

# Color shift tuning
COLOR_GRADIENT_MAX_SHIFT = 30   # +/- per-pixel 8-bit RGB offset, smoothly interpolated
COLOR_GRADIENT_GRID      = 4    # control-point grid size (larger = higher-frequency tint)
HUE_ROTATE_LIMIT         = 90   # OpenCV H units (0-179 scale). 90 = up to full half-rotation = red<->cyan etc.


# ---------------------------------------------------------------------------
# Derived helpers — keep the rest of the code free of if/else on LABEL_KIND
# ---------------------------------------------------------------------------
def resolved_labels_dir() -> Path:
    """Which label folder training/evaluation should read from."""
    return POLY_LABELS if LABEL_KIND == 'polygon' else BBOX_LABELS


def resolved_yolo_model() -> str:
    """Which COCO-pretrained base weights match the current LABEL_KIND."""
    return 'yolo11n-seg.pt' if LABEL_KIND == 'polygon' else 'yolo11n.pt'


def summary() -> None:
    print(f'LABEL_KIND={LABEL_KIND!r}')
    print(f'  labels   : {resolved_labels_dir()}')
    print(f'  images   : {IMAGES_DIR}')
    print(f'  base .pt : {resolved_yolo_model()}')
    print(f'  imgsz    : {IMAGE_SIZE}  |  val_fraction : {VAL_FRACTION}')
    print(f'  classes  : {CLASS_NAMES}')
